# Generated by Django 2.2.4 on 2022-02-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='팀이름')),
                ('description', models.TextField(verbose_name='내용')),
                ('type', models.CharField(max_length=100, verbose_name='점심종류')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project', verbose_name='식당 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
