# Generated by Django 2.2.4 on 2022-02-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_go', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='lunch_go',
        ),
    ]
